python3 format_sumstats.py \
    --sumstats 30804560-GCST007432-EFO_0004314.h.tsv.gz \
    --out FEV.txt \
    --sep '\t' \
    --A1 effect_allele \
    --A2 other_allele \
    --SNP variant_id \
    --CHR chromosome \
    --BP base_pair_location \
    --P p_value \
    --SE standard_error \
    --BETA beta \
    --FRQ effect_allele_frequency \
    --N n